name: Deploy Backend to EC2

on:
  push:
    branches: [main] # o master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/ciclomart_backend

            # Pull latest changes
            git pull origin main

            # Install dependencies (only if package.json changed)
            npm ci --production

            # Restart PM2
            pm2 reload ecosystem.config.js --env production --update-env

            # Show status PM2
            pm2 list
